paths:
  - Configuration

filePatterns:
  - "*.ts"

sniffs:
  - class: Indentation
    parameters:
      indentConditions: true
  - class: RepeatingRValue
    disabled: true
  - class: DeadCode
    disabled: true
